version: '3'

services:

#  nginx:
#    container_name: cs-nginx
#    image: nginx:1.13
#    restart: always
#    ports:
#      - 88:80
#      - 443:443
#    volumes:
#      - ./nginx.conf:/etc/nginx/conf.d/default.conf
#
  postgresql:
    container_name: cs-postgresql
    image: postgres:alpine
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=db-candy_shop
    ports:
      - 54321:5432
    volumes:
      - ./../.env/sql/:/docker-entrypoint-initdb.d

#  api:
#    container_name: cs-api
#    build: .
#    ports:
#      - 8084:8080
#    depends_on:
##      - nginx
#      - postgresql
##    command: mvn clean install spring-boot:run
